name: Go

on:
  push:
    branches:
      - main
      - "release-**"
  pull_request:
    branches:
      - main
      - "release-**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Vendor
        run: go work vendor

      - name: Build
        run: make

      - name: Install go-acc
        run: go install github.com/ory/go-acc@latest

      - name: Test Chai
        run: go-acc $(go list ./...) -- -mod vendor -race -timeout=2m

      - name: Test Chai CLI
        run: cd ./cmd/chai && go test -race ./... && cd -

      - name: Upload Codecov
        run: bash <(curl -s https://codecov.io/bash)
