name: Go

on:
  push:
    branches:
      - main
      - "release-**"
  pull_request:
    branches:
      - main
      - "release-**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build
        run: make

      - name: Test ChaiSQL
        run: go test -race -timeout=2m ./...
      
      - name: SQL tests
        run: cd ./sqltests && go test -race -timeout=2m ./... && cd -

      - name: Test Chai CLI
        run: cd ./cmd/chai && go test -race ./... && cd -
